
trigger:
- develop
- stage
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'ecommerce-connection-manual'
    azureResourceGroup: 'rg-ecommerce-prod'
    kubernetesCluster: 'aks-ecommerce-prod'
    manifests: 'k8s/*.yaml'



