trigger:
- dev
pr:
- dev
- master
- stage

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@4
  inputs:
    azureSubscription: 'ecommerce-connection-manual'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    #sonarQubeRunAnalysis: true
   # sqMavenPluginVersionChoice: 'latest'